### ISSUE TITLE
Shouldn't yup be added to the list of similar projects?

### ISSUE THREAD

**Issue by francescortiz** [michaljanocko/schemawax#11]

**Comment by francescortiz** [comment]
It works very similar:

https://github.com/jquense/yup

**Comment by michaljanocko** [comment]
Yes, it should. I only learned about it a couple days ago but I'm in the woods right now without access to a computer. I'm going to add it as soon as I get home.

This might be worth adding as well: [richardscarrott/ok-computer](https://github.com/richardscarrott/ok-computer)

**Comment by michaljanocko** [comment]
Done! :tada:
