### ISSUE TITLE
Recursive decoder example using `unknown`

### ISSUE THREAD

**Issue by francescortiz** [michaljanocko/schemawax#13]
I managed to have recursive decoders working. It requires you to add unknown as a potential value, so it implies some boilerplate code when handling the data (Array.isArray in the linked example at the bottom):

```typescript
type RecursiveType = {
  order: number;
  name: string;
  children?: RecursiveType[] | unknown;
};

const recursiveTypeDecoder_: D.Decoder<RecursiveType> = D.object({
  required: {
    order: D.number,
    name: D.string
  },
  optional: {
    children: D.unknown
  }
});

export const recursiveTypeDecoder: D.Decoder<RecursiveType> = recursiveTypeDecoder_.andThen(
  (v) => {
    return {
      ...v,
      children:
        v.children === undefined
          ? undefined
          : D.array(recursiveTypeDecoder).forceDecode(v.children)
    };
  }
);
```
You can see it working here:
https://codesandbox.io/s/node-ts-playground-forked-6wevw?file=/src/index.ts
_The example uses typescript 4.4.4 set up to be as strict as possible._

**Comment by francescortiz** [comment]
Hi, I saw you created a pull request. Nice! I will check it. On the other hand, I don't know exactly what you mean by dynamic children, so if you can elaborate I will clarify your doubts. Regarding recursive tuples, do you mean the following? 

```type RecursiveTuple = [RecursiveTuple, RecursiveTuple]```

**Comment by michaljanocko** [comment]
Yup, that's exactly what I meant with the tuples.
Or something even more complicated: `type User = [string, string, User[]]`
I was wondering if there could be a generic solution for all kinds of recursive types.
Doing recursive stuff in objects alone seems easy enough though.

**Comment by francescortiz** [comment]
Understood. I have extended the example. The idea is to allow `unknown` together with the recursive type. First, this makes sure that you have checked the type before using it, since there is no way to know with of the 2 decoders was used. Then, the actual recursive decoder starts from the non-recursive version that places unknowns, but then it calls itself within a function, which is the same trick that zod uses for lazy types, but with schemawax we get to infer the type.

**Comment by francescortiz** [comment]
Good news, I manage to create a type that automatically adds `| unknown`.:

```
export type Recursived<T, Ascendant = T> = T extends Array<Ascendant> // Arrays
  ? T[] | unknown
  : T extends Object
  ? {
      [U in keyof T]: Recursived<T[U], Ascendant>;
    }
  : T extends Ascendant
  ? T | unknown
  : T extends Array<infer U> // Arrays
  ? Recursived<U, Ascendant>[]
  : T extends Object
  ? {
      [U in keyof T]: Recursived<T[U], Ascendant>;
    }
  : T;
```

You can see it in action here:
https://codesandbox.io/s/node-ts-playground-forked-2g63u?file=/src/index.ts:58-442

This type might probably allow you to create and intermediate behind the scenes. Hope it helps.

**Comment by michaljanocko** [comment]
Well, it seems like I have been over-engineering everything in my explorations.
I have a working prototype that's nice and simple—just a few lines. I'm gonna do some work tomorrow but I make no promises. It will probably be done, tested, and deployed by the end of the week.

Also, do you have any preference for the function name?
```ts
D.recursive(() => /* Some decoder */)
```
```ts
D.lazy(() => /* Some decoder */)
```

I have arguments for both terms. "Lazy" is used almost everywhere; including the Elm language and the Zod library which both inspired Schemawax. Moreover, what it does is actually called _lazy_ decoding. However, I can't see a different use for it than _recursive_ decoders so "recursive" seems more specific and thus a bit clearer.

**Comment by francescortiz** [comment]
`recursive` states the use case, `lazy` states the technique used. I am in favor of stating the use case if it is clear. It is what people will look for, so it makes it more user friendly and will save time to the users. If, in the future, somebody comes with another use case for the `lazy` approach, an alias can be created with a deprecation notice for `recursive`. My 5 cents.

**Comment by michaljanocko** [comment]
Alright, #14 ready for more eyes to check. :eyes:

**Comment by michaljanocko** [comment]
Recursive decoders have been tested and deployed with version 1.0.7 just now! :rocket: Thanks for the idea and motivation!
