### ISSUE TITLE
Support creating readonly arrays

### ISSUE THREAD

**Issue by aszenz** [michaljanocko/schemawax#26]
Typescript has `ReadonlyArray<>` type, is there a way to create it from this library, I only see `D.array()`

**Comment by michaljanocko** [comment]
I don't think I understand correctly. Can you suggest what the API might look like? We need to create the array, so we would need to cast into a `readonly` later. Right?

**Comment by aszenz** [comment]
https://github.com/michaljanocko/schemawax/pull/27

**Comment by michaljanocko** [comment]
Closed together with #27.
